    LIST P=18F4550
    #INCLUDE<P18F4550.INC>
    
   #DEFINE BUTTON1 PORTE,RE0,0
   #DEFINE BUTTON2 PORTE,RE1,0
   #DEFINE LED PORTD,RD1,0
   
   ORG .0
   GOTO INICIO

DELAY_10mS
   CLRF	    TMR0L,0
   MOVLW    .39
ASK
   CPFSEQ   TMR0L,0
   RETURN
    
INICIO
   MOVLW    B'011'
   MOVWF    TRISE,0
   CLRF	    PORTE,0
   MOVLW    .15
   MOVWF    ADCON1,0
   
   MOVLW    .7
   MOVWF    CMCON,0
   
   CLRF	    TRISD,0
   MOVLW    B'01100000'
   MOVWF    OSCCON,0
   MOVLW    B'11010111'
   MOVWF    T0CON,0

MAIN
   BTFSC    LED
   GOTO	    OFF
   BTFSC    BUTTON1
NO GOTO	    MAIN
SI CALL	    DELAY_10mS
   BTFSS    BUTTON1
   GOTO	    SI
   GOTO	    RESPUESTA

OFF
   BTFSC    BUTTON2
NO2 GOTO	    MAIN
SI2 CALL	    DELAY_10mS
   BTFSS    BUTTON2
   GOTO	    SI2
   GOTO	    RESPUESTA2

RESPUESTA2
   BCF	    LED
   GOTO	    MAIN
RESPUESTA
   BSF	    LED
   GOTO	    MAIN
   END


